export const messagesFr = {
  required: "Ce champ est requis.",
  minLength: (min: number) => `Ce champ doit contenir au moins ${min} caractères.`,
  maxLength: (max: number) => `Ce champ ne peut pas dépasser ${max} caractères.`,
  email: "Veuillez saisir une adresse e-mail valide.",
  passwordMismatch: "Les mots de passe ne correspondent pas.",
  success: "Opération réussie.",
  error: "Une erreur est survenue.",
  erreurChargement: "Erreur de chargement",
  erreurEnregistrement: "Erreur lors de l'enregistrement",
  modifier: "Modifier",
  creer: "Créer",
  enregistrer: "Enregistrer",
  nomLabel: "Nom *",
  emailLabel: "Email *",
  telephoneLabel: "Téléphone *",
  adresseLabel: "Adresse",
  logoLabel: "Logo (URL)",
  deviseLabel: "Devise *",
  typePeriodeLabel: "Type de période *",
  mensuelle: "Mensuelle",
  hebdomadaire: "Hebdomadaire",
  journaliere: "Journalière",
  enregistrement: "Enregistrement...",
  connexion: "Connexion",
  bienvenue: "Bienvenue sur la gestion des salaires",
  adresseEmail: "Adresse email",
  motDePasse: "Mot de passe",
  seSouvenir: "Se souvenir de moi",
  motDePasseOublie: "Mot de passe oublié ?",
  connexionEnCours: "Connexion...",
  seConnecter: "Se connecter",
  ancienMotDePasseObligatoire: "Veuillez saisir votre ancien mot de passe.",
  nouveauMotDePasseCourt: "Le nouveau mot de passe doit contenir au moins 6 caractères.",
  erreurChangementMotDePasse: "Erreur lors du changement de mot de passe",
  changerMotDePasse: "Changer mon mot de passe",
  motDePasseChangeSucces: "Mot de passe changé avec succès !",
  valider: "Valider",
  changement: "Changement...",
  gestionEntreprises: "Gestion des entreprises",
  annuler: "Annuler",
  creerEntreprise: "Créer une entreprise",
  tableauBord: "Tableau de bord",
  suiviTempsReel: "Suivi en temps réel de la masse salariale, paiements et effectifs",
  masseSalarialeMois: "Masse salariale (ce mois)",
  montantPaye: "Montant payé",
  montantRestant: "Montant restant",
  employesActifs: "Employés actifs",
  nouveauxCeMois: "+2 nouveaux ce mois",
  derniersPaiements: "Derniers paiements enregistrés",
  prochainsPaiements: "Prochains paiements à effectuer",
  recu: "Reçu",
  entreprises: "Entreprises",
  employes: "Employés",
  cyclesPaie: "Cycles de paie",
  bulletinsPaie: "Bulletins de paie",
  paiements: "Paiements",
  documentsPdf: "Documents PDF",
  utilisateursRoles: "Utilisateurs & rôles",
  parametres: "Paramètres",
  deconnexion: "Déconnexion",
  supprimerEntreprise: "Supprimer cette entreprise ?",
  supprimer: "Supprimer cette entreprise ?",
  fermerEntreprise: "Fermer cette entreprise ?",
  erreurSupression: "Erreur lors de la suppression",
  erreurFermeture: "Erreur lors de la fermeture",
};
